apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-deploy
  labels:
    app: healthcare-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthcare-app
  template:
    metadata:
      labels:
        app: healthcare-app
    spec:
      containers:
      - name: healthcare-container
        image: kavipriyabai/healthcare-app
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-np-service
  labels:
    app: healthcare-app
spec:
  selector:
    app: healthcare-app  # Ensures the Service selects pods with this label

  type: NodePort
  ports:
    - port: 8082          # The port exposed inside the cluster
      targetPort: 8082    # Port where your container listens
      nodePort: 31034
